package backend.audit;

public enum AuditEventType {
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILURE,
    AUTH_ACCOUNT_LOCKED,
    AUTH_LOGOUT,
    SESSION_REGENERATED,
    SESSION_ANOMALY,
    RATE_LIMIT_BLOCKED,
    MESSAGE_SEND,
    MESSAGE_UNLOCKED,
    PUZZLE_CHALLENGE_ISSUED,
    PUZZLE_SOLVE_SUCCESS,
    PUZZLE_SOLVE_FAILURE,
    ADAPTIVE_ESCALATION,
    ADMIN_ACTION
}
